import { Router } from 'express';
import categoryRouter from '@category/category.router';
import authRouter from '@auth/auth.router';
import productRouter from '@product/product.router';
import userRouter from '@user/user.router';
import warehouseRouter from '@warehouse/warehouse.router';
import recipeRouter from '@recipe/recipe.router';
import mixtureRouter from '@mixture/mixture.router';
import manufactureRouter from '@manufacture/manufacture.router';
import rawMaterialRouter from '@raw-material/raw-material.router';
import mixtureMachineRouter from '@mixture-machine/mixture-machine.router';
import manufactureMachineRouter from '@manufacture-machine/manufacture-machine.router';
import warehouseMovementRouter from '@warehouse-movement/warehouse-movement.router';
import cartRouter from '@cart/cart.router';
import orderRouter from '@order/order.router';
import planningRouter from '@planning/planning.router';
import machineManagerRouter from '@machine-manager/machine-manager.router';
import productionPlanRouter from '@production-plan/production-plan.router';
import productionResultsRouter from '@production-results/production-results.router';

const router = Router();

router.use('/users', userRouter);
router.use('/products', productRouter);
router.use('/auth', authRouter);
router.use('/category', categoryRouter);
router.use('/warehouses', warehouseRouter);
router.use('/mixture-machine', mixtureMachineRouter);
router.use('/manufacture-machine', manufactureMachineRouter);
router.use('/recipes', recipeRouter);
router.use('/mixtures', mixtureRouter);
router.use('/manufactures', manufactureRouter);
router.use('/raw-material', rawMaterialRouter);
router.use('/warehouse-movement', warehouseMovementRouter);
router.use('/cart', cartRouter);
router.use('/order', orderRouter);
router.use('/plannings', planningRouter);
router.use('/machine-managers', machineManagerRouter);
router.use('/production-plans', productionPlanRouter);
router.use('/production-results', productionResultsRouter);

export default router;
